## Build
docker build -t udagram-api-feed ./udagram-api-feed
docker build -t udagram-api-user ./udagram-api-user
docker build -t udagram-frontend ./udagram-frontend
docker build -t reverseproxy ./reverseproxy
## Tagging 
docker tag udagram-api-feed trgnguyen/udagram-api-feed:v1
docker tag udagram-api-user trgnguyen/udagram-api-user:v1
docker tag udagram-frontend trgnguyen/udagram-frontend:v1
docker tag reverseproxy trgnguyen/reverseproxy:v1
```bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push trgnguyen/udagram-api-feed:v1
docker push trgnguyen/udagram-api-user:v1
docker push trgnguyen/udagram-frontend:v1
docker push trgnguyen/reverseproxy:v1