apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - name: "8100"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-frontend