apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: trgnguyen/udagram-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "600m"
          limits:
            memory: "2048Mi"
            cpu: "600m"