apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: trgnguyen/udagram-api-user:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "2048Mi"
            cpu: "600m"
          limits:
            memory: "2048Mi"
            cpu: "600m"     
        envFrom:
          - secretRef:
              name: env-secret
              optional: false
          - configMapRef:
              name: env-config
              optional: false
        env: 
          - name: 
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_USERNAME   